### ISSUE TITLE
Running VNN Partseg on ShapeNet data

### ISSUE THREAD

**Issue by AdeV-Oly** [FlyingGiraffe/vnn#12]
Hey there!

I'm interested in using this model for my own project, but I've run into a small problem during training for both the example/Shapenet dataset and my own dataset.

### Example data / ShapeNet data
So I've tried to run the example part segmentation on the ShapeNet data to see if it would even run on my system.
However, during training it returns a RunTimeError. If I remember correctly, the dimensions it returned were the following:

```
Traceback (most recent call last):
  File "/home/~/VNN/train_partseg.py", line 321, in <module>
    main(args)
  File "/home/~/VNN/train_partseg.py", line 205, in main
    seg_pred, trans_feat = classifier(points, to_categorical(label, num_classes))
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/~/VNN/models/vn_dgcnn_partseg.py", line 86, in forward
    l = self.conv7(l)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 298, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [90, 45, 3, 2], expected input[1, 15, 16, 32] to have 45 channels, but got 15 channels instead
```

Is this a known error for the example set?

Kind regards

**Comment by AdeV-Oly** [comment]
No idea what changed, but it somehow ran on the Shapenet data without giving this error.
