### ISSUE TITLE
Training VN_DGCNN_partseg on own dataset

### ISSUE THREAD

**Issue by AdeV-Oly** [FlyingGiraffe/vnn#13]
Hi there!

### Goal:
I'm trying to figure out how to train the VN_DGCNN on my own dataset for partial segmentation. I have just one folder (instead of 16 like in the ShapeNet dataset), i.e. one object I'd like to train this model on.

### Problem:
I assume I just need to alter the dataloader script (which I did; and the train-file naturally), but it's returning an error still. If I interpret the error correctly, it expects weights for 16 objects still? 

If anyone can point me into a certain direction, that'd be much appreciated!

### Error:
`Traceback (most recent call last):
  File "/home/~/VNN/train_partseg_US.py", line 320, in <module>
    main(args)
  File "/home/~/VNN/train_partseg_US.py", line 204, in main
    seg_pred, trans_feat = classifier(points, to_categorical(label, num_classes))
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/~/VNN/models/vn_dgcnn_partseg.py", line 86, in forward
    l = self.conv7(l)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/~/.conda/envs/VNN/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 298, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 16, 1], expected input[16, 1, 1] to have 16 channels, but got 1 channels instead
`

**Comment by AdeV-Oly** [comment]
Alright, so here's the story in short:

- I fixed it.
- I got the solution right away, weeks ago, but I adjusted the wrong model (vn_pointnet) by putting the number of classes (1 in this case) in the conv7 layer. So naturally nothing happened at that point. Derp.
- This was an unnecessary post, but hopefully still useful for amateurs like myself.

**Comment by acute0000** [comment]
Hi there!
I haved trained the VN_DGCNN model on my own dataset with 4096 point_num per PointCloud,while it took up a lot of video memory.When I set the batchsize to 22 with 4096 pointnum per frame, it almost took up totally 60G video memory  on three GeForce RTX 3090(with 24G per card).
So I would like to ask if you also have the problem of using too much memory during your training.
Thank you!
